name: housing
channels:
- conda-forge
- defaults
dependencies:
- python=3.9
- pandas=2.1.1
- scikit-learn=1.3.1
- numpy=1.24.3
- matplotlib=3.7.1
- seaborn=0.12.2
- fastapi==0.104.0
- uvicorn==0.23.2
- pandas==2.1.1
- scikit-learn==1.3.1
- python-multipart==0.0.6
- pydantic==2.4.2
- jupyter==1.0.0
- notebook==7.0.6 